# Generated by Django 2.0.1 on 2019-03-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('link_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Website')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Word')),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='word',
            field=models.ManyToManyField(through='search.WordWebsite', to='search.Word'),
        ),
    ]
