# Generated by Django 2.1.7 on 2019-04-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='title_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='link_text',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_text',
        ),
        migrations.AddField(
            model_name='website',
            name='root',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='search.Website'),
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, default=None, max_length=50),
        ),
    ]
