# Generated by Django 2.2 on 2019-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_website_click'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordWebsite',
            new_name='Have',
        ),
        migrations.RemoveField(
            model_name='website',
            name='root',
        ),
        migrations.AddField(
            model_name='website',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='website',
            name='ref',
            field=models.ManyToManyField(db_index=True, default=None, null=True, to='search.Website'),
        ),
    ]
