# Generated by Django 2.1.7 on 2019-04-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190423_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='website1',
            new_name='ref',
        ),
    ]
