# Generated by Django 2.1.7 on 2019-04-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190423_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='ref',
            field=models.ManyToManyField(db_index=True, default=None, null=True, to='search.Website'),
        ),
    ]
